---
test:
  ibm_cic_defaults: &ibm_cic_defaults
    hostname: ibm-cic
    port: 5000
    domain_id: default
    region: RegionOne
    security_protocol: ssl-no-validation
    username: username
    password: password
  ibm_cic:
    <<: *ibm_cic_defaults
