=begin
#Site Manager API

#Site Manager API

The version of the OpenAPI document: 3.2.14
Contact: autosde@il.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

module AutosdeOpenapiClient
  VERSION = '3.2.14'
end
