---
:ems:
  :ems_ansible_tower:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:http_proxy:
  :ansible_tower:
    :host:
    :password:
    :port:
    :user:
:ems_refresh:
  :ansible_tower_automation:
    :allow_targeted_refresh: true
    :inventory_collections:
      :saver_strategy: batch
    :refresh_interval: 15.minutes
:log:
  :level_ansible_tower: info
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_ansible_tower:
        :poll: 20.seconds
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_ansible_tower_automation: {}
