---
test:
  ibm_power_vc_defaults: &ibm_power_vc_defaults
    hostname: powervc.local
    user_id: user
    password: password
    image: image
    network: network
  ibm_power_vc:
    <<: *ibm_power_vc_defaults
