apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-account
  namespace: default
---
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: my-account
  namespace: default
---
