apiVersion: v1
kind: Template
metadata:
  name: working
  annotations:
    description: OCP KubeVirt Fedora 27 VM template
    iconClass: icon-fedora
    tags: kubevirt,ocp,template,linux,virtualmachine
  creationTimestamp: null
  labels:
    kubevirt.io/os: fedora27
    miq.github.io/kubevirt-is-vm-template: "true"
objects:
- apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachine
  metadata:
    creationTimestamp: null
    labels:
      kubevirt-vm: vm-${NAME}
      kubevirt.io/os: fedora27
    name: ${NAME}
  spec:
    running: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          kubevirt-vm: vm-${NAME}
          kubevirt.io/os: fedora27
      spec:
        domain:
          cpu:
            cores: ${{CPU_CORES}}
          resources:
            requests:
              memory: ${MEMORY}
          devices:
            disks:
            - disk:
                bus: virtio
              name: registryvolume
            - disk:
                bus: virtio
              name: cloudinitvolume
          machine:
            type: ""
        terminationGracePeriodSeconds: 0
        volumes:
        - name: registryvolume
          containerDisk:
            image: kubevirt/fedora-cloud-registry-disk-demo:latest
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitvolume
  status: {}
parameters:
- description: Name for the new VM
  name: NAME
- description: Amount of memory
  name: MEMORY
  value: 1Gi
- description: Amount of cores
  name: CPU_CORES
  value: "4"
