Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - attr_from_hash
    - raise
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%w': '[]'
    '%W': '[]'
