---
test:
  ibm_power_hmc_defaults: &ibm_power_hmc_defaults
    username: ibm-power-hmc-username
    password: ibm-power-hmc-password
    hostname: ibm-power-hmc-hostname
  ibm_power_hmc:
    <<: *ibm_power_hmc_defaults
