---
:ems:
  :ems_kubevirt:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:workers:
  :worker_base:
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_kubevirt: {}
