---
test:
  vmware_cloud_defaults: &vmware_cloud_defaults
    host: vmwarecloudhost
    userid: VMWARE_CLOUD_USERID
    password: VMWARE_CLOUD_PASSWORD
  vmware_cloud:
    <<: *vmware_cloud_defaults
  vmware_infra_defaults: &vmware_infra_defaults
    hostname: HOSTNAME
  vmware_infra:
    <<: *vmware_infra_defaults
  vmware_tanzu_defaults: &vmware_tanzu_defaults
    hostname: vmware-tanzu-hostname
    userid: VMWARE_TANZU_USERID
    password: VMWARE_TANZU_PASSWORD
  vmware_tanzu:
    <<: *vmware_tanzu_defaults
