# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs

  extensions:
  - .mjs
  - .js
  - .jsx
  - .ts
  - .tsx
  - .sass
  - .scss
  - .css
  - .png
  - .svg
  - .gif
  - .jpeg
  - .jpg

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
