=begin
#Site Manager API

#Site Manager API

The version of the OpenAPI document: 1.0.0
Contact: autosde@il.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'cgi'

module AutosdeOpenapiClient
  class CeleryConfigApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # @param [Hash] opts the optional parameters
    # @return [Array<CeleryConfig>]
    def celery_config_get(opts = {})
      data, _status_code, _headers = celery_config_get_with_http_info(opts)
      data
    end

    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<CeleryConfig>, Integer, Hash)>] Array<CeleryConfig> data, response status code and response headers
    def celery_config_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CeleryConfigApi.celery_config_get ...'
      end
      # resource path
      local_var_path = '/celery-config'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<CeleryConfig>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"CeleryConfigApi.celery_config_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CeleryConfigApi#celery_config_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # @param celery_config [CeleryConfig] 
    # @param [Hash] opts the optional parameters
    # @return [CeleryConfig]
    def celery_config_post(celery_config, opts = {})
      data, _status_code, _headers = celery_config_post_with_http_info(celery_config, opts)
      data
    end

    # @param celery_config [CeleryConfig] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(CeleryConfig, Integer, Hash)>] CeleryConfig data, response status code and response headers
    def celery_config_post_with_http_info(celery_config, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CeleryConfigApi.celery_config_post ...'
      end
      # verify the required parameter 'celery_config' is set
      if @api_client.config.client_side_validation && celery_config.nil?
        fail ArgumentError, "Missing the required parameter 'celery_config' when calling CeleryConfigApi.celery_config_post"
      end
      # resource path
      local_var_path = '/celery-config'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(celery_config)

      # return_type
      return_type = opts[:debug_return_type] || 'CeleryConfig'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"CeleryConfigApi.celery_config_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CeleryConfigApi#celery_config_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
