=begin
#Site Manager API

#Site Manager API

The version of the OpenAPI document: 1.0.0
Contact: autosde@il.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'cgi'

module AutosdeOpenapiClient
  class HostClusterMembershipApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # @param [Hash] opts the optional parameters
    # @return [Array<HostClusterMembership>]
    def host_cluster_membership_get(opts = {})
      data, _status_code, _headers = host_cluster_membership_get_with_http_info(opts)
      data
    end

    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<HostClusterMembership>, Integer, Hash)>] Array<HostClusterMembership> data, response status code and response headers
    def host_cluster_membership_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HostClusterMembershipApi.host_cluster_membership_get ...'
      end
      # resource path
      local_var_path = '/host-cluster-membership'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<HostClusterMembership>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"HostClusterMembershipApi.host_cluster_membership_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HostClusterMembershipApi#host_cluster_membership_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # @param pk [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [AsyncResponse]
    def host_cluster_membership_pk_delete(pk, opts = {})
      data, _status_code, _headers = host_cluster_membership_pk_delete_with_http_info(pk, opts)
      data
    end

    # @param pk [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(AsyncResponse, Integer, Hash)>] AsyncResponse data, response status code and response headers
    def host_cluster_membership_pk_delete_with_http_info(pk, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HostClusterMembershipApi.host_cluster_membership_pk_delete ...'
      end
      # verify the required parameter 'pk' is set
      if @api_client.config.client_side_validation && pk.nil?
        fail ArgumentError, "Missing the required parameter 'pk' when calling HostClusterMembershipApi.host_cluster_membership_pk_delete"
      end
      # resource path
      local_var_path = '/host-cluster-membership/{pk}'.sub('{' + 'pk' + '}', CGI.escape(pk.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"HostClusterMembershipApi.host_cluster_membership_pk_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HostClusterMembershipApi#host_cluster_membership_pk_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # @param pk [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [HostClusterMembership]
    def host_cluster_membership_pk_get(pk, opts = {})
      data, _status_code, _headers = host_cluster_membership_pk_get_with_http_info(pk, opts)
      data
    end

    # @param pk [Integer] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(HostClusterMembership, Integer, Hash)>] HostClusterMembership data, response status code and response headers
    def host_cluster_membership_pk_get_with_http_info(pk, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HostClusterMembershipApi.host_cluster_membership_pk_get ...'
      end
      # verify the required parameter 'pk' is set
      if @api_client.config.client_side_validation && pk.nil?
        fail ArgumentError, "Missing the required parameter 'pk' when calling HostClusterMembershipApi.host_cluster_membership_pk_get"
      end
      # resource path
      local_var_path = '/host-cluster-membership/{pk}'.sub('{' + 'pk' + '}', CGI.escape(pk.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'HostClusterMembership'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"HostClusterMembershipApi.host_cluster_membership_pk_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HostClusterMembershipApi#host_cluster_membership_pk_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # @param host_cluster_membership [HostClusterMembership] 
    # @param [Hash] opts the optional parameters
    # @return [AsyncResponse]
    def host_cluster_membership_post(host_cluster_membership, opts = {})
      data, _status_code, _headers = host_cluster_membership_post_with_http_info(host_cluster_membership, opts)
      data
    end

    # @param host_cluster_membership [HostClusterMembership] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(AsyncResponse, Integer, Hash)>] AsyncResponse data, response status code and response headers
    def host_cluster_membership_post_with_http_info(host_cluster_membership, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HostClusterMembershipApi.host_cluster_membership_post ...'
      end
      # verify the required parameter 'host_cluster_membership' is set
      if @api_client.config.client_side_validation && host_cluster_membership.nil?
        fail ArgumentError, "Missing the required parameter 'host_cluster_membership' when calling HostClusterMembershipApi.host_cluster_membership_post"
      end
      # resource path
      local_var_path = '/host-cluster-membership'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(host_cluster_membership)

      # return_type
      return_type = opts[:debug_return_type] || 'AsyncResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"HostClusterMembershipApi.host_cluster_membership_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HostClusterMembershipApi#host_cluster_membership_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
