=begin
#Site Manager API

#Site Manager API

The version of the OpenAPI document: 1.0.0
Contact: autosde@il.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'cgi'

module AutosdeOpenapiClient
  class ServiceResourcesComplianceApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # @param service_resources_compliance [ServiceResourcesCompliance] 
    # @param [Hash] opts the optional parameters
    # @return [ServiceResourcesComplianceResponse]
    def service_resources_compliance_post(service_resources_compliance, opts = {})
      data, _status_code, _headers = service_resources_compliance_post_with_http_info(service_resources_compliance, opts)
      data
    end

    # @param service_resources_compliance [ServiceResourcesCompliance] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(ServiceResourcesComplianceResponse, Integer, Hash)>] ServiceResourcesComplianceResponse data, response status code and response headers
    def service_resources_compliance_post_with_http_info(service_resources_compliance, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ServiceResourcesComplianceApi.service_resources_compliance_post ...'
      end
      # verify the required parameter 'service_resources_compliance' is set
      if @api_client.config.client_side_validation && service_resources_compliance.nil?
        fail ArgumentError, "Missing the required parameter 'service_resources_compliance' when calling ServiceResourcesComplianceApi.service_resources_compliance_post"
      end
      # resource path
      local_var_path = '/service-resources-compliance'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(service_resources_compliance)

      # return_type
      return_type = opts[:debug_return_type] || 'ServiceResourcesComplianceResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"ServiceResourcesComplianceApi.service_resources_compliance_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ServiceResourcesComplianceApi#service_resources_compliance_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
