sudo: false
language: ruby
cache: bundler
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install:
  - "echo 'gem: --no-ri --no-rdoc --no-document' > ~/.gemrc"
  - "gem install bundler -v 1.13.0"
