---
:ems:
  :ems_redfish:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :general:
          :critical:
          - /^redfish_/
:http_proxy:
  :redfish:
    :host:
    :password:
    :port:
    :user:
:workers:
  :worker_base:
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_redfish_physical_infra: {}
    :event_catcher:
      :event_catcher_redfish: {}
